### ISSUE TITLE
Is it possible to add a reindex api for git hooks?

### ISSUE THREAD

**Issue by aki-colt** [sourcebot-dev/sourcebot#113]
Notice that the index could be only reindexed while restart. Could it be possible to add a reindex api for git hooks to reindex when new commit or new branch is added?

**Comment by brendan-kellam** [comment]
Heya - there is no reindexing api atm, but could be an interesting addition to include with #101. Currently, reindexing happens [once per hour](https://github.com/sourcebot-dev/sourcebot/blob/f71a83a941fed8920626ad02e74a6aa9de246558/packages/backend/src/main.ts#L277). What is your use case? Is it often you want to search on new commits / branches as soon as they are pushed to the remote?

Also, what code host are you using? Assuming it has webhook support, I wonder if #57 would be preferred for this use case instead of using git hooks.

**Comment by aki-colt** [comment]
Yes, what I mentioned is similar to #57, my fault that didn't notice that. I am in a special condition that I use gitlab to host not code but some docs which need to be version controlled and also need to be searched. Since there is a need to search in real time so I care about real time reindexing. I think an api for reindex is not difficult to implement after a quick browse to source code, but my concern is whether there is a performance issue in the index engine with frequent reindexing due to frequent commits.

**Comment by brendan-kellam** [comment]
Are you using Sourcebot on your local machine? If so, one work-around that you could try is to use local indexing with the watch-mode enabled. Any changes made within the specified `path` will be re-indexed automatically:

```jsonc
{
    "$schema": "./schemas/v2/index.json",
    "repos": [
        {
            "type": "local",
            "path": "/path/to/my/repo",
            "watch": true
        }
    ]
}
```

If not local, then yea we will either need a webhook support or a REST api.

In terms of performance issues, I think that would depend on the frequency at which a re-indexing occurs and the size of the repo that is being indexed.. so best bet will be to for us to benchmark, see where the limits are, and go from there.

**Comment by aki-colt** [comment]
Thanks very much for the help. I am going on a test on  if there is a performance issue.

**Comment by brendan-kellam** [comment]
Sounds good - let me know if you run into any issues for it. Going to close this issue for now, but please feel free to re-open.
