### ISSUE TITLE
Sync all GitLab repos visible to the token

### ISSUE THREAD

**Issue by loris** [sourcebot-dev/sourcebot#49]
Not sure if a bug report or a feature request, but it looks like v2 does not allow to sync all the repositories of a GitLab server which are visible to the user who created the token.

According to the documentation it should be possible using `groups`: "List of groups to sync with. All projects in the group visible to the provided `token` (if any) will be synced.". However this is not how it works because of the hardcoded `owned=true` query parameter: https://github.com/sourcebot-dev/sourcebot/blob/3697f3da7f421a1634c4adffa2909ac7203ca6a3/packages/backend/src/gitlab.ts#L26-L29

In addition to that `owned=true` query parameter which should be removed IMO, we should probably allow syncing all the projects of a gitlab server when neither `groups` or `users` or `projects` are defined (using `api.Projects.all()`)

Currently, the only workaround to sync all the visible repos seems to explicitly list them all in the `projects` property

**Comment by brendan-kellam** [comment]
thanks for raising! Yea I think the `owned=true` was a oversight on my part since I was always testing with projects that I owned. Fix for that incoming in #50. Update: Fixed in release [v2.1.1](https://github.com/sourcebot-dev/sourcebot/releases/tag/v2.1.1)

I will keep this issue open for the suggestion about syncing all projects visible to a token.

**Comment by Jellyfrog** [comment]
`include_subgroups` option is missing, in v1 I didn't need to specify anything, in v2 I need to specify every single group I want indexed
